### ISSUE TITLE
configure path for erl_crash.dump

### ISSUE THREAD

**Issue by ioolkos** [erlio/vmq_server#101]
Setting `-env ERL_CRASH_DUMP /erl_crash.dump` possibly prevents erl_crash.dump from being written.

**Comment by dergraf** [comment]
should be adressed in erlio/vernemq I think

**Comment by ioolkos** [comment]
Can be set in `vernemq.conf`, if needed:
`erlang.crash_dump = ./log/erl_crash.dump`
