### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by ghost** [erlio/vmq_server#36]
HI,

I am new to common test framework.I tried with all the commands but I am not able to run them.Could you please help in running the test suites in vmq_server/test directory?

Thank you...

Best Regards,
shahid.

**Comment by larshesel** [comment]
Hi,

You can run all the common test suites when you're in the `vmq_server` directory by issuing:

```
  ./rebar3 ct
```

You can read more about how to run common test suites with rebar3 over here: http://www.rebar3.org/docs/running-tests#common-test.

Please feel free to reopen if you run into any issues regarding running the common tests.

**Comment by ghost** [comment]
Hi,

Thank you for your quick response..

I have tried the command but not able run the suites.
I am getting the below crash reports after running the ./rebar3 ct
`ubuntu@ip-172-31-30-116:~/vmq_server$ ./rebar3 ct
===> Verifying dependencies...
===> Linking /home/ubuntu/vmq_server/_build/default/lib/clique to /home/ubuntu/vmq_server/_build/test/lib/clique
===> Linking /home/ubuntu/vmq_server/_build/default/lib/cowboy to /home/ubuntu/vmq_server/_build/test/lib/cowboy
===> Linking /home/ubuntu/vmq_server/_build/default/lib/cuttlefish to /home/ubuntu/vmq_server/_build/test/lib/cuttlefish
===> Linking /home/ubuntu/vmq_server/_build/default/lib/epmdpxy to /home/ubuntu/vmq_server/_build/test/lib/epmdpxy
===> Linking /home/ubuntu/vmq_server/_build/default/lib/exometer_core to /home/ubuntu/vmq_server/_build/test/lib/exometer_core
===> Linking /home/ubuntu/vmq_server/_build/default/lib/jobs to /home/ubuntu/vmq_server/_build/test/lib/jobs
===> Linking /home/ubuntu/vmq_server/_build/default/lib/lager to /home/ubuntu/vmq_server/_build/test/lib/lager
===> Linking /home/ubuntu/vmq_server/_build/default/lib/plumtree to /home/ubuntu/vmq_server/_build/test/lib/plumtree
===> Linking /home/ubuntu/vmq_server/_build/default/lib/riak_sysmon to /home/ubuntu/vmq_server/_build/test/lib/riak_sysmon
===> Linking /home/ubuntu/vmq_server/_build/default/lib/sext to /home/ubuntu/vmq_server/_build/test/lib/sext
===> Linking /home/ubuntu/vmq_server/_build/default/lib/vmq_commons to /home/ubuntu/vmq_server/_build/test/lib/vmq_commons
===> Linking /home/ubuntu/vmq_server/_build/default/lib/vmq_plugin to /home/ubuntu/vmq_server/_build/test/lib/vmq_plugin
===> Linking /home/ubuntu/vmq_server/_build/default/lib/cowlib to /home/ubuntu/vmq_server/_build/test/lib/cowlib
===> Linking /home/ubuntu/vmq_server/_build/default/lib/edown to /home/ubuntu/vmq_server/_build/test/lib/edown
===> Linking /home/ubuntu/vmq_server/_build/default/lib/eleveldb to /home/ubuntu/vmq_server/_build/test/lib/eleveldb
===> Linking /home/ubuntu/vmq_server/_build/default/lib/folsom to /home/ubuntu/vmq_server/_build/test/lib/folsom
===> Linking /home/ubuntu/vmq_server/_build/default/lib/getopt to /home/ubuntu/vmq_server/_build/test/lib/getopt
===> Linking /home/ubuntu/vmq_server/_build/default/lib/goldrush to /home/ubuntu/vmq_server/_build/test/lib/goldrush
===> Linking /home/ubuntu/vmq_server/_build/default/lib/meck to /home/ubuntu/vmq_server/_build/test/lib/meck
===> Linking /home/ubuntu/vmq_server/_build/default/lib/neotoma to /home/ubuntu/vmq_server/_build/test/lib/neotoma
===> Linking /home/ubuntu/vmq_server/_build/default/lib/parse_trans to /home/ubuntu/vmq_server/_build/test/lib/parse_trans
===> Linking /home/ubuntu/vmq_server/_build/default/lib/ranch to /home/ubuntu/vmq_server/_build/test/lib/ranch
===> Linking /home/ubuntu/vmq_server/_build/default/lib/riak_dt to /home/ubuntu/vmq_server/_build/test/lib/riak_dt
===> Linking /home/ubuntu/vmq_server/_build/default/lib/setup to /home/ubuntu/vmq_server/_build/test/lib/setup
===> Linking /home/ubuntu/vmq_server/_build/default/lib/bear to /home/ubuntu/vmq_server/_build/test/lib/bear
===> Compiling vmq_server
===> Running Common Test suites...

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.533.0>},
                       {name,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.534.0>},
                       {name,overload},
                       {mfargs,{overload,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.532.0>},
                       {name,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.535.0>},
                       {name,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: sasl
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.541.0>},
                       {name,disksup},
                       {mfargs,{disksup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.542.0>},
                       {name,memsup},
                       {mfargs,{memsup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.544.0>},
                       {name,cpu_sup},
                       {mfargs,{cpu_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: os_mon
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,riak_sysmon_sup}
             started: [{pid,<0.551.0>},
                       {name,riak_sysmon_filter},
                       {mfargs,{riak_sysmon_filter,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,riak_sysmon_sup}
             started: [{pid,<0.552.0>},
                       {name,riak_sysmon_mgr},
                       {mfargs,
                           {gen_event,start_link,
                               [{local,riak_sysmon_handler}]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: riak_sysmon
          started_at: 'vmq_server@ip-172-31-30-116'
Setup running ...
Directories verified. Res = {[ok],[]}

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: setup
          started_at: 'vmq_server@ip-172-31-30-116'
Setup finished processing hooks ...

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.563.0>},
                       {name,exometer_admin},
                       {mfargs,{exometer_admin,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.564.0>},
                       {name,exometer_cache},
                       {mfargs,{exometer_cache,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.565.0>},
                       {name,exometer_report},
                       {mfargs,{exometer_report,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.566.0>},
                       {name,exometer_report_logger_sup},
                       {mfargs,{exometer_report_logger_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.567.0>},
                       {name,exometer_folsom_monitor},
                       {mfargs,{exometer_folsom_monitor,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,exometer_core_sup}
             started: [{pid,<0.568.0>},
                       {name,exometer_alias},
                       {mfargs,{exometer_alias,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: exometer_core
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,jobs_app}
             started: [{pid,<0.573.0>},
                       {name,jobs_server},
                       {mfargs,{jobs_server,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,jobs_app}
             started: [{pid,<0.574.0>},
                       {name,jobs_sampler},
                       {mfargs,{jobs_sampler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: jobs
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: eleveldb
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: riak_dt
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
         application: sext
          started_at: 'vmq_server@ip-172-31-30-116'

=PROGRESS REPORT==== 1-Feb-2016::14:28:07 ===
          supervisor: {local,plumtree_sup}
             started: [{pid,<0.582.0>},
                       {name,plumtree_metadata_leveldb_iterator_sup},
                       {mfargs,
                           {plumtree_metadata_leveldb_iterator_sup,
                               start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,supervisor}]
enif_send: env==NULL on non-SMP VM[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
Aborted (core dumped)
ubuntu@ip-172-31-30-116:~/vmq_server$
`
**Machine Details:**
`ubuntu@ip-172-31-30-116:~/vmq_server$ uname -a
Linux ip-172-31-30-116 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-30-116:~/vmq_server`

I rebuilt  the Erlang OTP using the below command but issue is still there
./configure --enable-smp-support

Similar ticket on SMP issue.
https://github.com/erlio/vernemq/issues/67 

Please help me in this issue.

**Comment by larshesel** [comment]
So the error seems to indicate that either your erlang was not configured with SMP support (even though you specified it to the config script) or erlang is not starting in SMP mode.

Can you try and start the erlang shell: `erl` and show us the output?

Ff you have smp enabled by default you should see the [smp:X:X]. If you don't see that then try and start erlang with `erl -smp enable` to check if it was just not enabled or if your erlang version was build without it.

On my local machine it looks like this:

``` erlang
$ erl
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
```

It's unfortunately not possible to pass the '-smp enable' field to the `rebar3` version we ship, I asked about it over on the freenode IRC channel and this was what I was told:

```
<larshesel> Hi - didn't find it in the docs, but maybe I missed it. Is there  way to pass options to the erlang runtime when running common tests under rebar3. I'm in particular thinking about the '-smp enable | disable' flag...
<tristan__> larshesel: yes, it is new and not dcoumented yet. if you install rebar3 with 'rebar3 local install' you can then use:
<tristan__> REBAR3_ERL_ARGS="..." rebar3 <task>
<tristan__> this only works when used with the unpacked rebar that gets installed to ~/.cache/rebar3/bin
```

I haven't tried this yet, though.

**Comment by ghost** [comment]
HI,
I ran the erl command on the terminal.It is not showing smp while starting.
**ubuntu@ip-172-31-30-116:~/otp_src_17.5$ erl
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1>
**
after enabling the smp flag

**ubuntu@ip-172-31-30-116:~/otp_src_17.5$ erl -smp enable
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:1:1] [async-threads:10] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1>
**
I am using amazon cloud services for the installation.Please let me know a way to resolve this issue.

**Comment by larshesel** [comment]
To make sure erlang is started with smp when running common tests I only know of the undocumented rebar3 feature I mentioned above. Here's how it worked for me:

``` shell
$ git clone https://github.com/rebar/rebar3
Cloning into 'rebar3'...
...
$ cd rebar3/ && ./bootstrap && ./rebar3 local install
===> Verifying dependencies...
===> Fetching bbmustache ({pkg,<<"bbmustache">>,<<"1.0.4">>})
[removed for brevity]
===> Extracting rebar3 libs to /home/lhc/.cache/rebar3/lib...
===> Writing rebar3 run script /home/lhc/.cache/rebar3/bin/rebar3...
===> Add to $PATH for use: export PATH=$PATH:/home/lhc/.cache/rebar3/bin
```

The version of `rebar3` you need to use is now installed in `~/.cache/rebar3/bin`. Go to you vmq_server directory and issue:

``` shell
REBAR3_ERL_ARGS='-smp enable' ~/.cache/rebar3/bin/rebar3  ct
```

I belive the reason erlang does not start with SMP support by default on a single-core machine like the one you're running is that it does not make sense from a performance perspective. So if the above does not work, a workaround could be to use a machine with more cores. Note actually running VerneMQ on a machine with only one core should be possible as mentioned in erlio/vernemq#67.

**Comment by ghost** [comment]
Hi,

Thank you very much for your help.The above solution is working.

**Comment by ghost** [comment]
Hi Again,

I am able to run the test suites.I would like to enable the DBG traces on vmq_mqtt_fsm.erl module.
I tried all the shell with rebar3 command but this didn't work.

Could you please tell me how to login into the vmq_server erlang shell and enbling the DBG traces while running the test suites ?

Thank you in advance..

**Comment by larshesel** [comment]
Hi

In order to run common tests from the shell, please consult the common test documentation: http://erlang.org/doc/apps/common_test/run_test_chapter.html. I haven't tried to do this myself, though.

Another approach is to run test a specific test case directly (without using the ct framework):

``` erlang
$ erl -pa ./_build/test/lib/*/test/ -pa _build/test/lib/*/ebin 
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
1> l(vmq_cluster_SUITE).
{module,vmq_cluster_SUITE}
2> vmq_cluster_SUITE:init_per_suite([]).
...
3> C = vmq_cluster_SUITE:init_per_testcase([], []).
4> vmq_cluster_SUITE:multiple_connect_unclean_test(C).
!!!!!!!!!!!!!!!!!!! Subs before send {[[{total,1}],
                                       [{total,1}],
                                       [{total,1}],
                                       [{total,1}],
                                       [{total,1}]],
                                      []}
!!!!!!!!!!!!!!!!!!! stored msgs before send {[0,0,0,0,0],[]}
.....................................................................
```

But maybe you could explain to us what you're trying to achieve?
