### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by brangi** [erlio/vmq_server#6]
Using the paho android client library...I am getting this error in the broker and the client disconnects

2015-06-01 15:37:40.840 [debug] <0.2493.0>@vmq_session_proxy:handle_info:87 ['VerneMQ@192.168.1.56'][{[],"mqttjs334389048b872a533002b34d73f8c29fd09efc50"}] stopped message replication for subscriber 'VerneMQ@192.168.1.56' due to deliver_from_store proc stopped normally
2015-06-01 15:37:41.564 [warning] <0.2490.0>@vmq_ranch:teardown:121 [<0.2491.0>] session stopped
                       abnormally due to parse_error

**Comment by dergraf** [comment]
Hi Gibran, which version of the paho android client are you using?

**Comment by ghost** [comment]
@dergraf I am getting the same error using latest `paho` (`1.0.2`). Can you please shed some light?

**Comment by dergraf** [comment]
can you provide the link to the library, and the configuration of your CONNECT and PUBLISH message?

**Comment by ghost** [comment]
@dergraf  The library can be obtained from here: http://www.eclipse.org/paho/ . The Maven repo for the release version sits at https://repo.eclipse.org/content/repositories/paho-releases/ . The configuration for the client is the following:

``` java
MqttConnectOptions connOpt = new MqttConnectOptions();

connOpt.setCleanSession(clean);
connOpt.setKeepAliveInterval(300);
connOpt.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);

MqttAsyncClient client = new MqttAsyncClient("tcp://127.0.0.1:1883", "paho-client", new MemoryPersistence());

client.connect(connOpt, new IMqttActionListener() {
  @Override
  public void onSuccess(IMqttToken iMqttToken) {
    // ...
  }

  @Override
  public void onFailure(IMqttToken iMqttToken, Throwable throwable) {
    // ...
  }
});
```

**Comment by ghost** [comment]
This is what gets dumped to VerneMQ's `console.log`:

```
2015-07-24 11:38:53.462 [debug] <0.503.0>@vmq_ranch:handle_message:220 [tcp][<0.504.0>] parse error for data: <<48,71,0,45,[...]...>> and  parser state: <<>>
2015-07-24 11:38:53.462 [warning] <0.503.0>@vmq_ranch:teardown:120 [<0.504.0>] session stopped
                       abnormally due to parse_error
2015-07-24 11:39:03.299 [debug] <0.508.0>@vmq_session:handle_event:288 [<0.508.0>] stop in state connected due to disconnect
2015-07-24 11:39:03.400 [debug] <0.507.0>@vmq_ranch:teardown:116 [<0.508.0>] session normally stopped
```

**Comment by dergraf** [comment]
``` java
package io.erl;
import org.eclipse.paho.client.mqttv3.*;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

public class Main {

    public static void main(String[] args) {

        String broker       = "tcp://127.0.0.1:1883";
        String clientId     = "paho-client";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttAsyncClient sampleClient = new MqttAsyncClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            connOpts.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);
            System.out.println("Connecting to broker: " + broker);
            sampleClient.connect(connOpts, new IMqttActionListener() {
                        @Override
                        public void onSuccess(IMqttToken iMqttToken) {
                            System.out.println("Connected");
                        }

                        @Override
                        public void onFailure(IMqttToken iMqttToken, Throwable throwable) {
                            System.out.println("Cant connect");
                        }
                    });
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
    }
}
```

This is working for me, using the async and sync MQTT Client implementation. Using https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.2/org.eclipse.paho.client.mqttv3-1.0.2.jar

**Comment by ghost** [comment]
@dergraf in my case it only happens when publishing a large number of messages in a short period of time. Can it be related to some kind of throttling or to the size of the TCP buffers?

**Comment by dergraf** [comment]
what do you mean by large amount? Do you random generate Topic Strings?

**Comment by ghost** [comment]
@dergraf I am load testing some brokers, VerneMQ included. So, indeed, I am generating (a huge load of) messages containing a timestamp and publishing them to a dynamically generated topic string (`topic/{client-id}/{message-id}`).

**Comment by dergraf** [comment]
ok, what do you include in your topic string? 
can you try to:

``` erlang
vmq_topic:validate({publish, "my/topic/string"}).
```

in the erlang shell? (vernemq attach)

**Comment by ghost** [comment]
@dergraf This is what I get:

``` erlang
(VerneMQ@127.0.0.1)2> vmq_topic:validate({publish, "lt/0a115968-a253-4d50-ba07-a8c4c532e314/365"}).
true
```

**Comment by dergraf** [comment]
I should have checked your debug log first...
is it possible that your connecting with a Client ID that is already used by another Session? In this case we forcefully disconnect the old session.

**Comment by ghost** [comment]
@dergraf No, that's not the case. Every client ID is unique.

**Comment by dergraf** [comment]
can you provide a binary dump?
e.g. run redbug:start("vmq_parser:parse").

**Comment by ghost** [comment]
```
(VerneMQ@127.0.0.1)1> redbug:start("vmq_parser:parse").
{200,2}

% 15:48:35 <0.4165.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16,48,0,4,77,81,84,84,4,2,1,44,0,36,49,53,51,102,50,101,54,53,45,100,57,102,
  57,45,52,53,101,98,45,56,55,54,52,45,49,100,57,53,101,99,50,48,98,54,99,98>>)

% 15:48:35 <0.4165.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16>>, <<0,4,77,81,84,84,4,2,1,44,0,36,49,53,51,102,50,101,54,53,45,100,57,102,57,45,
  52,53,101,98,45,56,55,54,52,45,49,100,57,53,101,99,50,48,98,54,99,98>>)

% 15:48:35 <0.4177.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16,48,0,4,77,81,84,84,4,2,1,44,0,36,99,57,53,97,101,102,98,55,45,50,48,56,
  102,45,52,101,52,101,45,56,102,57,50,45,54,98,53,99,99,99,54,50,48,55,100,48>>)

% 15:48:35 <0.4177.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16>>, <<0,4,77,81,84,84,4,2,1,44,0,36,99,57,53,97,101,102,98,55,45,50,48,56,102,45,
  52,101,52,101,45,56,102,57,50,45,54,98,53,99,99,99,54,50,48,55,100,48>>)

% 15:48:35 <0.4173.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16,48,0,4,77,81,84,84,4,2,1,44,0,36,101,101,55,54,49,98,56,52,45,53,48,99,51,
  45,52,50,98,48,45,98,50,51,99,45,98,53,55,53,52,102,99,49,52,50,56,55>>)

% 15:48:35 <0.4173.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16>>, <<0,4,77,81,84,84,4,2,1,44,0,36,101,101,55,54,49,98,56,52,45,53,48,99,51,45,52,
  50,98,48,45,98,50,51,99,45,98,53,55,53,52,102,99,49,52,50,56,55>>)

% 15:48:35 <0.4171.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16,48,0,4,77,81,84,84,4,2,1,44,0,36,48,101,57,48,52,98,56,97,45,52,100,97,49,
  45,52,99,51,56,45,56,100,57,53,45,98,52,100,97,57,48,98,98,53,97,100,48>>)

% 15:48:35 <0.4171.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16>>, <<0,4,77,81,84,84,4,2,1,44,0,36,48,101,57,48,52,98,56,97,45,52,100,97,49,45,52,
  99,51,56,45,56,100,57,53,45,98,52,100,97,57,48,98,98,53,97,100,48>>)

% 15:48:35 <0.4175.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16,48,0,4,77,81,84,84,4,2,1,44,0,36,49,101,98,57,51,100,98,51,45,53,50,52,
  100,45,52,55,101,53,45,56,50,57,49,45,51,51,102,50,55,54,56,50,55,100,57,97>>)

% 15:48:35 <0.4175.0>({vmq_ranch,init,4})
% vmq_parser:parse(<<16>>, <<0,4,77,81,84,84,4,2,1,44,0,36,49,101,98,57,51,100,98,51,45,53,50,52,100,45,
  52,55,101,53,45,56,50,57,49,45,51,51,102,50,55,54,56,50,55,100,57,97>>)
redbug done, msg_count - 10
```

**Comment by dergraf** [comment]
sorry could you retry with
`redbug:start("vmq_parser:parse -> return", [{print_re, "error"}]).`

**Comment by ghost** [comment]
@dergraf Nothing hapens. It just prints this:

``` erlang
(VerneMQ@127.0.0.1)1> redbug:start("vmq_parser:parse -> return", [{print_re, "error"}]).
{3272,2}
redbug done, noproc - 6
```

**Comment by dergraf** [comment]
sorry, my bad: next try:
`redbug:start("vmq_parser:parse -> return", [{time, 60000}, {msgs, 100000}, {print_file, "/tmp/verne_trace.out"}]).`

This will give enough time for the trace (1 minute) to trace 100k messages (hope that's enough). The generated trace file will contain all the function calls together with their parameters and return values. Once you see the parse_error popping up in the console.log you can run redbug:stop() to stop the trace.
After that you could quickly grep the /tmp/verne_trace.out for the string error and paste here the  ~20 lines before the occurrence of the error string.

Sorry that it is that cumbersome.. I see big potential to improve this kind of debugging in an upcoming version. (btw.. does it mean that your other issue regarding building VerneMQ is fixed?)

**Comment by ghost** [comment]
@dergraf Ok, will try right now. As for the other issue, it somehow ony occurs on my Ubuntu machines. I'm building and running this on a spare Arch Linux box, where the error doesn't occur.

**Comment by ghost** [comment]
@dergraf Is it possible that, although the error did occur, no `error` string was written to `/tmp/verne_trace.out`?

**Comment by dergraf** [comment]
hmm you still see parse_error in the console.log?

**Comment by ghost** [comment]
@dergraf Yes.

**Comment by dergraf** [comment]
hmm, it's getting weird.. could you come over to freenode #vernemq so we could discuss it over there?

**Comment by dergraf** [comment]
better logging of parse errors is now an own issue in https://github.com/erlio/vmq_server/issues/17

**Comment by dergraf** [comment]
I've updated vmq_commons to include the bug fix @bmcustodio already tested. Does it solve your (@brangi) problem too? Just run `./rebar3 upgrade vmq_commons` and then `make rel` again.

**Comment by dergraf** [comment]
can we close this issue @brangi @bmcustodio ? I think 0.11.1 contains all the bugfixes required for this.

**Comment by dergraf** [comment]
I close this for now. Feel free to reopen it if required.
