### ISSUE TITLE
Invalid commit for cuttlefish dependency on master

### ISSUE THREAD

**Issue by essen** [erlio/vmq_server#7]
The commit doesn't exist and so the project fails to build.

**Comment by dergraf** [comment]
sorry for that. most folks were cloning the umbrella repo erlio/vernemq.git which had the dependencies locked. we now made the switch to rebar3, and everything should be working again.

**Comment by essen** [comment]
Can't add the vernemq repository as dependency which is why I add those to erlang.mk's index. Will try after the current round of testing is done, cheers.

**Comment by dergraf** [comment]
I understand! :) Thanks
