### ISSUE TITLE
Netmap or dpdk support.

### ISSUE THREAD

**Issue by harmoniqpunk** [erlio/vmq_server#71]
Hi,

I need a serious dataplane that support millions of connections and for this reason I would like to add dpdk or netmap support for vernemq. Any "best practice" advice from you ?
Basically I thought to use [edpdk](https://github.com/FlowForwarding/edpdk) on top of a dpdk kubernetes network manager. 

However I'm new in Erlang. I love it but I don't have experience so any advice from you would be great. Thank you.

**Comment by dergraf** [comment]
I played with netmap and Erlang a while ago. The main issue I found was that the Erlang VM on my laptop couldn't cope with the millions of packets ingested. But, yeah havent had time to work further on that front.

**Comment by harmoniqpunk** [comment]
Thank you !

**Comment by dergraf** [comment]
let's close this for now. but please keep us posted on your progress! :)

**Comment by harmoniqpunk** [comment]
Yes, I forgot. Thank you! I'll come with update. I will implement dpdk and then I'll come with update.

**Comment by eshikafe** [comment]
I think it will be better to do your userplane in C/C++ or Rust and your control plane in Erlang.
