### ISSUE TITLE
Errno 104 Connection reset by peer

### ISSUE THREAD

**Issue by GavinDmello** [erlio/vmq_server#85]
I was load testing verne with 10 clients concurrently sending 20000 messages each. Sometimes the I get reset error and then the client doesn't receive any more messages after that.

**Comment by ioolkos** [comment]
Hi @GavinDmello 
thanks for letting us know!
Is there any more information you could provide? clients or testing framework used?

**Comment by GavinDmello** [comment]
I used mqtt malaria to simulate the clients.  Once you install it.  You can run `./malaria subscribe -n 20000 -N 10 -H 'Hostname'`  to run the receivers and `./malaria publish -t -n 20000 -P 10 -H 'hostname'` for the publishers.

**Comment by ioolkos** [comment]
OK, there's a couple of things to realize when testing this way.
First you have 10 processes trying to get rid of 20k messages as fast as possible (QoS 1 style). They are received by a single subscriber on the other side. This either creates instant overload (with message dropping) for that consumer. Or, you configure a huge max_online_messages queue, and then wait for the subscriber to slowly consumer all those messages. So, the only thing you're actually testing is the message delivery throughput for a single subscriber for your system (network and disk).

This doesn't explain the 104 connection reset, of course.

**Comment by GavinDmello** [comment]
That's exactly what we wanted to test. I've increased the max online messages to -1 (which I know is not recommended) .

**Comment by ioolkos** [comment]
Ok, great :)
Let us know how your testing is going in any case.

**Comment by GavinDmello** [comment]
Is there any limitation on the number of topics and subscriptions per node and in a clustered setup ?

**Comment by ioolkos** [comment]
Hi @GavinDmello 
Not theoretically, but it's of course memory-bound.

**Comment by GavinDmello** [comment]
Are there any numbers on topics/subscriptions I could make for 8 gigs of RAM ? We're expecting at least 12 million subscribers

**Comment by ioolkos** [comment]
This is probably going to need lots of RAM. It entirely depends on the whole topic/subscriber situation:
- How long are ClientIDs
- How long and nested are topics
- How many subscriptions per ClientID (and does each subscribe to its own exclusive topic)

Feel free to mail us for some clearer estimate based on your information.
