### ISSUE TITLE
Repeated process crashes related metrics counter

### ISSUE THREAD

**Issue by ephe-meral** [erlio/vmq_server#89]
After running VMQ for a while and having several hundreds of (re)-connects, it keeps logging crashes in a metrics counter.

I'm not sure what it is related to, but I can try to investigate if you can give me hint of what to look for.

```
09:30:13.974 [error] gen_server vmq_metrics terminated with reason: bad argument in call to mzmetrics:update_resource_counter(<<>>, 0, 341606371714284795) in lists:foreach/2 line 1337
09:30:13.974 [error] CRASH REPORT Process vmq_metrics with 0 neighbours exited with reason: bad argument in call to mzmetrics:update_resource_counter(<<>>, 0, 341606371714284795) in lists:foreach/2 line 1337
09:30:13.976 [error] Supervisor vmq_metrics_sup had child undefined started with vmq_metrics:start_link() at <0.25047.25> exit with reason bad argument in call to mzmetrics:update_resource_counter(<<>>, 0, 341606371714284795) in lists:foreach/2 line 1337 in context child_terminated
09:30:13.976 [debug] Supervisor vmq_metrics_sup started vmq_metrics:start_link() at pid <0.25029.25>
09:30:14.976 [error] GenServer :vmq_metrics terminating
** (ArgumentError) argument error
    (mzmetrics) :mzmetrics.update_resource_counter("", 0, 341606371714284803)
    (stdlib) lists.erl:1337: :lists.foreach/2
    (vmq_server) /home/vagrant/vernemq/distdir/0.13.1/_build/default/lib/vmq_server/src/vmq_metrics.erl:486: :vmq_metrics.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :calc_rates
State: {:state}
```

**Comment by dergraf** [comment]
Hi!

This looks like a 'stupid' counter overflow bug.
Does it work again if you run `vmq-admin metrics reset`?

Best,
Andre

**Comment by ephe-meral** [comment]
Hi Andre - this is something I can't do, since we're running this in a container on an EC2 instance in prod and getting a console to this is close to not possible...

**Comment by dergraf** [comment]
Sorry, but this is currently the only workaround I can offer. 

I've investigated a bit and it looks we should replace/rewrite part of the mzmetrics library we're using.

**Comment by ephe-meral** [comment]
But do you know how this affects the operation of VMQ? I can also observe this every now and then, btw:

```
14:49:55.013 [error] Supervisor vmq_metrics_sup had child undefined started with vmq_metrics:start_link() at <0.4366.27> exit with reason reached_max_restart_intensity in context shutdown
14:49:55.013 [error] Supervisor vmq_server_sup had child undefined started with vmq_metrics_sup:start_link() at <0.4355.27> exit with reason shutdown in context child_terminated
14:49:55.013 [debug] Supervisor vmq_metrics_sup started vmq_metrics:start_link() at pid <0.4369.27>
14:49:55.013 [debug] Supervisor vmq_metrics_sup started vmq_graphite:start_link() at pid <0.4368.27>
14:49:55.014 [debug] Supervisor vmq_metrics_sup started vmq_systree:start_link() at pid <0.4348.27>
14:49:55.014 [debug] Supervisor vmq_server_sup started vmq_metrics_sup:start_link() at pid <0.4367.27>
```

So I guess it escalates to supervisor crashes - dunno how that affects VMQ in the long run.

**Comment by dergraf** [comment]
This PR is going through review at the moment https://github.com/erlio/mzmetrics/pull/1

**Comment by larshesel** [comment]
Hi @ephe-meral I just merged the PR.

@dergraf @ioolkos I guess we should create a new release with this fix?

**Comment by larshesel** [comment]
@ephe-meral vernemq master branch is now using the fixed mzmetrics dependency. I hope that will do until we build an official patch release.

**Comment by ephe-meral** [comment]
@dergraf @larshesel Thanks for the quick reaction! We're using the package to build the VMQ docker container, so I'll need to wait for the release ;)
